### ISSUE TITLE
RBAC with domains model returns false for all enforcements

### ISSUE THREAD

**Issue by anton-khodak** [casbin/casbin#163] opened 2018-11-19 09:17 UTC
https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_model.conf
https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_policy.csv

`main.go`

```go
package main

import "github.com/casbin/casbin"

func main() {
	e := casbin.NewEnforcer("models/rbac_with_domains_model.conf", "models/rbac_with_domains_model.csv")
	e.Enforce("alice","domain1", "data1", "read")
	e.Enforce("admin", "domain1", "data1", "read")
	e.Enforce("alice","domain1", "data1", "write")
	e.Enforce("alice","domain2", "data2", "write")
	e.Enforce("bob", "domain2", "data2", "write")
}
```

`go build main.go` output:

```sh
2018/11/19 09:15:43 Model:
2018/11/19 09:15:43 e.e: some(where (p_eft == allow))
2018/11/19 09:15:43 m.m: g(r_sub, p_sub, r_dom) && r_dom == p_dom && r_obj == p_obj && r_act == p_act
2018/11/19 09:15:43 g.g: _, _, _
2018/11/19 09:15:43 r.r: sub, dom, obj, act
2018/11/19 09:15:43 p.p: sub, dom, obj, act
2018/11/19 09:15:43 Request: alice, domain1, data1, read ---> false
2018/11/19 09:15:43 Request: admin, domain1, data1, read ---> false
2018/11/19 09:15:43 Request: alice, domain1, data1, write ---> false
2018/11/19 09:15:43 Request: alice, domain2, data2, write ---> false
2018/11/19 09:15:43 Request: bob, domain2, data2, write ---> false
```

**Comment by hsluoyz** [comment] 2018-11-19 11:02
The following test has passed in Travis.

https://github.com/casbin/casbin/blob/02f3171fc71e510cfce0e120dc511cf784e421bd/model_test.go#L149-L160

**Comment by anton-khodak** [comment] 2018-11-19 11:44
Can you please try running the code above? For some reason, it works OK when paths are absolute, but gives "falses" if paths are relative.

**Comment by hsluoyz** [comment] 2018-11-19 12:14
I can't reproduce your error. You need to provide a runnable Git repository, which clearly shows the error.

**Comment by anton-khodak** [comment] 2018-11-19 13:19
Oh, the error was that I passed a non-existent file `models/rbac_with_domains_model.csv` as a policy file. Probably, the enforcer should fail explicitly in this case.

**Comment by hsluoyz** [comment] 2018-11-19 13:21
I already encountered the panic, didn't you see it?

```
C:\GoPath\src\github.com\casbin\casbin\main>go run main.go
panic: open examples/rbac_with_domains_model.conf: The system cannot find the path specified.

goroutine 1 [running]:
github.com/casbin/casbin/model.Model.LoadModel(0xc00006c720, 0x577528, 0x25)
        C:/GoPath/src/github.com/casbin/casbin/model/model.go:96 +0x18e
github.com/casbin/casbin.NewModel(0xc00007dd28, 0x2, 0x2, 0x40bedf)
        C:/GoPath/src/github.com/casbin/casbin/enforcer.go:147 +0x70
github.com/casbin/casbin.(*Enforcer).InitWithAdapter(0xc0000a2000, 0x577528, 0x25, 0x593720, 0xc00004c470)
        C:/GoPath/src/github.com/casbin/casbin/enforcer.go:109 +0x74
github.com/casbin/casbin.(*Enforcer).InitWithFile(0xc0000a2000, 0x577528, 0x25, 0x5771e6, 0x24)
        C:/GoPath/src/github.com/casbin/casbin/enforcer.go:104 +0x8a
github.com/casbin/casbin.NewEnforcer(0xc00007de28, 0x2, 0x2, 0x110)
        C:/GoPath/src/github.com/casbin/casbin/enforcer.go:73 +0x181
main.main()
        C:/GoPath/src/github.com/casbin/casbin/main/main.go:6 +0x8f
exit status 2
```

**Comment by hsluoyz** [comment] 2018-11-19 13:51
This issue is fixed in: https://github.com/casbin/casbin/commit/287dc513fa6e1e83f4959b1f4e8eaa8ae3962d7f

**Closed** 2018-11-19 13:51 UTC
