### ISSUE TITLE
[Bug] Implicit role doesn't work in go-lang lib but work in casbin editor

### ISSUE THREAD

**Issue by longsunli** [casbin/casbin#1204] opened 2023-03-01 15:26 UTC
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**Describe the bug**
We are using RBAC with domain model  to do authorization. And using group policy to extend one role to another. 

In the casbin editor below we can see that `can_manage` extends `can_use` role in all domain, and user with `can_manage` role can also perform `can_use` action like attach. 

https://editor.casbin.org/#DQV237WAL

<img width="1563" alt="image" src="https://user-images.githubusercontent.com/17940602/222183677-539cc0f7-b36f-4de8-bff7-b68cf5f82ded.png">

But same logic doesn't work in casbin go-lang lib even latest  version `v2.64.0`

**To Reproduce**
Code example

```
package main

import (
	"log"

	"github.com/casbin/casbin/v2"
	casbinModel "github.com/casbin/casbin/v2/model"
)

const (
	modelText = `
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
#RBAC
m = g(r.sub, p.sub, r.dom) && keyMatch(r.dom, p.dom) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act) 
`
)

func main() {

	m, err := casbinModel.NewModelFromString(modelText)
	if err != nil {
		panic(err)
	}
	e, err := casbin.NewSyncedEnforcer(m)
	if err != nil {
		panic(err)
	}

	e.AddPolicy("can_manage", "engines/*", "*", "(pause)|(resume)")
	e.AddPolicy("can_use", "engines/*", "*", "(attach)|(detach)")

	e.AddGroupingPolicy("can_manage", "can_use", "*")
	e.AddGroupingPolicy("Username==test2", "can_manage", "engines/engine1")

	implicitRoles, _ := e.GetImplicitRolesForUser("Username==test2", "engines/engine1")
	log.Println(implicitRoles)
        // can_manage

	ok, _, _ := e.EnforceEx("Username==test2", "engines/engine1", "*", "attach")
	log.Println(ok)
        // false
}

```

**Expected behavior**
`implicitRoles` should be `can_manage` and `can_use` and ok should be `true`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by longsunli** [comment] 2023-03-01 15:40
It doesn't work even I set domain to `engines/*`
```
	e.AddGroupingPolicy("can_manage", "can_use", "engines/*")
```

And it finally work if I specifically set domain to `engines/engine1`
```
	e.AddGroupingPolicy("can_manage", "can_use", "engines/engine1")
```

Specifically set domain to detail value will cause so many group policies, which looks not good and also impact performance.

**Comment by longsunli** [comment] 2023-03-01 15:42
Another option is I put `can_use` actions to `can_manage`, this will make policy not clear. 

So it's better to fix this issue and make sure go-lang lib perform same behavior like casbin editor.

**Comment by hsluoyz** [comment] 2023-03-01 15:54
@PokIsemaine @JalinWang

**Comment by PokIsemaine** [comment] 2023-03-03 03:00
@longsunli Thank you for your feedback!

It seems that currently casbin(go) believes that domain "*" and domain "engines/engine1" do not contain relationships, which causes this problem.

If you change the `domain "*"` to the `domain "engines/engine1"`, the result is exactly as expected
![image](https://user-images.githubusercontent.com/46661603/222620018-045a3a15-4223-479d-a5dd-f3735e2109af.png)

![image](https://user-images.githubusercontent.com/46661603/222620197-8aae8c1d-d145-4d41-bdce-4f4185da35db.png)

I plan to identify the cause and fix it in the coming days

**Comment by PokIsemaine** [comment] 2023-03-09 14:34
@hsluoyz Some functions pass a domain parameter but don't actually use and handle it, I try to fix it but ran into some difficulties

**Comment by xuantianyingjie** [comment] 2023-03-11 13:45
在查看了最新版本后，我发现在DomainManager中无法获得domain的keymatch函数。如果在判断用户的角色或权限之前添加一句注册keymatch函数的代码，似乎可以解决这个问题

**Comment by xuantianyingjie** [comment] 2023-03-11 14:44
> 

hello，after I modify the following code, I can get the correct result. However, I don't know how to get the domain keymatch function in modeltext, nor how to get the name parameter in the middle of the AddNamedDomainMatchingFunc function. If it is the default rolemanager, can it be modified like this?
```
func (e *Enforcer) initRmMap() {
	for ptype := range e.model["g"] {
		if rm, ok := e.rmMap[ptype]; ok {
			_ = rm.Clear()
		} else {
			e.rmMap[ptype] = defaultrolemanager.NewRoleManager(10)
			e.AddNamedDomainMatchingFunc(ptype, "g", util.KeyMatch)
		}
	}
}
```

**Comment by xuantianyingjie** [comment] 2023-03-11 14:45
> @hsluoyz Some functions pass a domain parameter but don't actually use and handle it, I try to fix it but ran into some difficulties

hello，after I modify the following code, I can get the correct result. However, I don't know how to get the domain keymatch function in modeltext, nor how to get the name parameter in the middle of the AddNamedDomainMatchingFunc function. If it is the default rolemanager, can it be modified like this?
```
func (e *Enforcer) initRmMap() {
	for ptype := range e.model["g"] {
		if rm, ok := e.rmMap[ptype]; ok {
			_ = rm.Clear()
		} else {
			e.rmMap[ptype] = defaultrolemanager.NewRoleManager(10)
			e.AddNamedDomainMatchingFunc(ptype, "g", util.KeyMatch)
		}
	}
}
```

**Comment by PokIsemaine** [comment] 2023-03-12 10:25
@xuantianyingjie Thanks for the suggestion， However, if `KeyMatch` is added by default, the following situation does not seem to meet expectations.

Model domain does not use `KeyMatch` , but `r.dom == p.dom`


```golang
const (
	modelText = `
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
#RBAC
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act) 
`
)

func TestDemo(t *testing.T) {

	m, err := casbinModel.NewModelFromString(modelText)
	if err != nil {
		panic(err)
	}
	e, err := NewSyncedEnforcer(m)
	if err != nil {
		panic(err)
	}

	e.AddPolicy("can_manage", "engines/*", "*", "(pause)|(resume)")
	e.AddPolicy("can_use", "engines/*", "*", "(attach)|(detach)")

	e.AddGroupingPolicy("can_manage", "can_use", "*")
	e.AddGroupingPolicy("Username==test2", "can_manage", "engines/engine1")

	e.GetRoleManager().AddDomainMatchingFunc("g", util.KeyMatch)
	implicitRoles, _ := e.GetImplicitRolesForUser("Username==test2", "engines/engine1")
	log.Println(implicitRoles)
	// should be [can_manage] but [can_manage can_user]

	ok, _, _ := e.EnforceEx("Username==test2", "engines/engine1", "*", "attach")
	log.Println(ok)
	// false
}
```

**Comment by PokIsemaine** [comment] 2023-03-12 10:29
> > @hsluoyz Some functions pass a domain parameter but don't actually use and handle it, I try to fix it but ran into some difficulties
> 
> hello，after I modify the following code, I can get the correct result. However, I don't know how to get the domain keymatch function in modeltext, nor how to get the name parameter in the middle of the AddNamedDomainMatchingFunc function. If it is the default rolemanager, can it be modified like this?
> 
> ```
> func (e *Enforcer) initRmMap() {
> 	for ptype := range e.model["g"] {
> 		if rm, ok := e.rmMap[ptype]; ok {
> 			_ = rm.Clear()
> 		} else {
> 			e.rmMap[ptype] = defaultrolemanager.NewRoleManager(10)
> 			e.AddNamedDomainMatchingFunc(ptype, "g", util.KeyMatch)
> 		}
> 	}
> }
> ```

This is a good suggestion, and I would consider adding functions based on model

**Comment by longsunli** [comment] 2023-03-29 07:25
@PokIsemaine @hsluoyz Do we have any process on this?

**Comment by PokIsemaine** [comment] 2023-03-29 07:47
> @PokIsemaine @hsluoyz Do we have any process on this?

Sorry, the progress of this issue has been temporarily put on hold due to personal reasons (I have been busy recently).
@hsluoyz  plz assign this task to someone else first

**Closed** 2023-04-05 01:21 UTC
Labels: bug

**Comment by longsunli** [comment] 2023-04-06 05:53
Thanks, I will verify with latest release `2.66.2`

**Comment by longsunli** [comment] 2023-04-10 13:06
Verify with latest release v2.66.3. Thanks guys
